apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-ztp-sno15
  namespace: ztp-clusters
spec:
  clusterConditions:
    - type: "ManagedClusterJoined"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: "ztp-sno15"
