apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: operator-configs-ztp-sno15-subscription
  namespace: ztp-clusters
  labels:
    app: operator-configs-ztp-sno15
  annotations:
    apps.open-cluster-management.io/git-path: examples/rhacm/cnf-config/sites/ztp-sno15/
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      kind: PlacementRule
      name: cluster-ztp-sno15
