apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-deployments
  namespace: ztp-clusters
  annotations:
    apps.open-cluster-management.io/deployables: ''
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - cluster-deployments
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cluster-deployments-subscription
  namespace: ztp-clusters
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: examples/rhacm/clusters/
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cluster-deployments
    app.kubernetes.io/part-of: cluster-deployments
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      name: local-cluster-placement
      kind: PlacementRule
