apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local-cluster-placement
  namespace: ztp-clusters
  annotations: {}
  labels:
    app: cluster-deployments
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
